### ISSUE TITLE
documentation: import vs require

### ISSUE THREAD

**Issue by MarcVanDaele90** [examind-ai/ltijs-firestore#4]
I'm no nodejs expert (at all) so I have a, hopefully, trivial question

The documentation states 
```
import Firestore from '@examind/ltijs-firestore';

lti.setup(
  'LTIKEY',
  { plugin: new Firestore() }
);
```
 But when using this inside my existing index.js (which contains ao my firebase cloud functions) I get the following error

``` 
import Firestore from '@examind/ltijs-firestore';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```
So I probably need to use `require` somehow but I'm not sure how this should look.  For example, the following code
```
const firebase = require('@examind/ltijs-firestore');
lti.setup(
  'LTIKEY',
  { plugin: new Firestore() }
);
```
results in `ReferenceError: Firestore is not defined`.

Can you add an example using `require` to the documentation?

**Comment by johnnyoshika** [comment]
I updated the documentation [here](https://github.com/examind-ai/ltijs-firestore#installation) with an example on how to use `require`. I'm fairly new to JavaScript's module system as well, so please let me know if that works. [This technique](https://github.com/examind-ai/ltijs-firestore/blob/main/test/0-provider.js#L20) worked in my unit tests, so I'm hoping it works for the general CommonJS use case as well.

I find the `{ default: Firestore }` syntax pretty ugly, so I'll probably go away from using default exports in the next iteration of this plugin.

**Comment by MarcVanDaele90** [comment]
Thanks!
