### ISSUE TITLE
Can't find ltik token

### ISSUE THREAD

**Issue by hailstorm46** [examind-ai/ltijs-firestore#5]
Hi there! 

I'm working on setting up ltijs as middleware so it can be the go between for my frontend and server. I saw in the [documentation ](https://cvmcosta.me/ltijs/#/provider?id=bearer-authorization-header) and [comment](https://github.com/examind-ai/ltijs-firestore/issues/3#issuecomment-1199955523) by @johnnyoshika that there should be an ltik token passed back as a query parameter on a successful connection. I'm not seeing that token anywhere. I followed the same general setup mentioned here:

> Assuming you've already got something like the demo-server working, to use LTIJS as a middleware, you need to set [ltiaas](https://cvmcosta.me/ltijs/#/provider?id=ltiaas-mode) to `true` during `lti.setup()`. This is my setup:
> 
> ```
> lti.setup(
>   process.env.LTI_KEY,
>   {
>     plugin: new Firestore(),
>   },
>   {
>     cookies: {
>       secure: true, // Set secure to true if the testing platform is in a different domain and https is being used
>       sameSite: 'None', // Set sameSite to 'None' if the testing platform is in a different domain and https is being used
>     },
>     devMode: false,
>     ltiaas: true, // Disables cookie validation (set this to true when using LTIJS as a middleware)
>     dynReg: {
>       url: `${process.env.SERVER_URL}/`,
>       name: 'COMPANY NAME',
>       logo: 'https://url-to-logo.com',
>       description: 'LTI integration',
>       autoActivate: false, // Whether or not dynamically registered Platforms should be automatically activated. Defaults to false.
>     },
>   },
> );
> ```
> 
> 
> LTIJS will pass along an `ltik` query string parameter to the redirect URL you specify above, so your client app can now include that `ltik` value when sending LTI requests to your main server. Your main server will then act as a proxy and use that `ltik` when making requests to the `ltiServer`. When doing so, add this HTTP header:
> 
> ```
> Authorization: LTIK-AUTH-V1 Token={ltik},Additional=Bearer {your_secret}
> ```
> 
> Where `{ltik}` is the ltik sent from your client and `{your_secret}` is any secret that you want to pass to ltiServer. When LTIJS parses your `Authorization` header, it'll validate `ltik` and replace `req.headers.authorization` with this:
> 
> ```
> Bearer {your_secret}
> ```

The request gets to the onConnect function just fine, but when it redirects there is no ltik token (no query parameters at all). Here's what my function looks like:

```
lti.onConnect(async (token, req, res) => {
  console.log('Connected!');
  console.log(token);
  return res.redirect(301, process.env.frontEndURL + '/login');
});
```

The token printed has a ton of info on the user, platform, etc. but nothing labeled 'ltik'. Is the ltik token the same as the onConnect function token parameter?

**Comment by johnnyoshika** [comment]
You use should use this:

```
return lti.redirect(res, process.env.frontEndURL + '/login');
```

Instead of this:

```
return res.redirect(301, process.env.frontEndURL + '/login');
```

**Comment by hailstorm46** [comment]
I tried changing it but I get this error:

 GMT express deprecated res.redirect(url, status): Use res.redirect(status, url) instead

UnhandledPromiseRejectionWarning: RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code

**Comment by hailstorm46** [comment]
Nevermind, it was a typo. This worked:

```
return lti.redirect(res, process.env.frontEndURL + '/login');
```
