### ISSUE TITLE
Firebase Authentication

### ISSUE THREAD

**Issue by hades5a** [examind-ai/ltijs-firestore#6]
Good evening,
I am currently developing an app which uses ltijs and your magnificent firestore plugin. I have wondered if there is an option to authenticate as an user somehow? Given the case that only documents should be readable if: 
1. It is the right user trying to access his data or
2. A teacher

How would you solve that?

**Comment by johnnyoshika** [comment]
This plugin and LTIJS are meant to run in a trusted environment of the server and it doesn't provide any end user authentication. Your service that uses LTIJS would need to ensure that requests are allowed before LTIJS (and therefore ltijs-firestore) are called. Something like this:

![image](https://user-images.githubusercontent.com/504505/213361520-9c8dcffe-3319-4ccf-a5f0-882e399a7596.png)

**Comment by johnnyoshika** [comment]
As a suggestion, I recommend you set up LTIJS as a middleware. Here's a diagram of how you can do that: https://github.com/examind-ai/ltijs-firestore/issues/3#issuecomment-1198368085
